#!/usr/bin/perl

my @classes = (
    "NotImplemented",
    "InvalidArgument",
    "InvalidHandle",
    "FileReadError",
    "FileWriteError",
    "BreakException",
    "InvalidAddress",
    "InvalidAlignment",
    "AccessViolation",
    "InvalidInstruction",
    "ArimethicOverflow",
    "InternalError",
    "UnkownError"
);

foreach my $class (@classes) {
    print "
    const char * $class", "Exception::to_c_str() const {
        return \"$class\";
    }
";
    
}
